### ISSUE TITLE
Making this part of official Quartz

### ISSUE THREAD

**Issue by lahma** [zlzforever/Quartz.AspNetCore#2]
I'm reaching out to ask whether you would be willing to contribute your work and the NuGet package id to official Quartz project? I'd like to have maintained release part of the Quartz repository and organisation. I found out about this project when I was making sure that the `Quartz.AspNetCore` package id is still free - which it was not. Ideally original package reserves the sub-package ids... Now I would need to create some artificial name like `Quartz.AspNetCoreOfficial` or something.

**Comment by zlzforever** [comment]
@lahma what's your usename in nuget.org, i will add you as a owner.

**Comment by lahma** [comment]
Thank you for your prompt reply, my username is same as here `lahma`, you can verify Quartz ownership of the username here https://www.nuget.org/packages/Quartz/ . I'm really glad that you are open for the idea 👍

**Comment by zlzforever** [comment]
done. please approve my request

**Comment by lahma** [comment]
Accepted the request, thank you very much! I'll close this issue, you should see support as part of release 3.1. Thanks again.

**Comment by lahma** [comment]
I'm happy to inform you that I've just successfully pushed a new version of the package, 3.1 beta 1. Thank you for your help again!
