### ISSUE TITLE
useless redundant code

### ISSUE THREAD

**Issue by fudiwei** [zlzforever/Quartz.AspNetCore#3]
Hi, I just found there are two lines code in **src/Quartz.AspNetCore/ServiceCollectionExtensions.cs**.

https://github.com/zlzforever/Quartz.AspNetCore/blob/06b4da8caf99531a5cb977d3ff5237a62c0ebf31/src/Quartz.AspNetCore/ServiceCollectionExtensions.cs#L27

https://github.com/zlzforever/Quartz.AspNetCore/blob/06b4da8caf99531a5cb977d3ff5237a62c0ebf31/src/Quartz.AspNetCore/ServiceCollectionExtensions.cs#L28

It seems to be wrote repeatly twice by mistake.

**Comment by zlzforever** [comment]
done
