### ISSUE TITLE
typo mistake

### ISSUE THREAD

**Issue by fudiwei** [zlzforever/Quartz.AspNetCore#4]
Hi, I think there is a typo mistake in:

https://github.com/zlzforever/Quartz.AspNetCore/blob/06b4da8caf99531a5cb977d3ff5237a62c0ebf31/src/Quartz.AspNetCore/QuartzOtpionsBuilder.cs#L9

`QuartzOtpions` should be `QuartzOptions`.

Would you like to correct this, and then upgrade the nuget package?

Thank you.

**Comment by zlzforever** [comment]
done
